ROLE_SCOPES = {
    "administrator": [
        "ad:ar",
        "ad:rr",
        "ad:cp",
        "ad:gr",
        "ga:cr",
        "ga:re",
        "ga:up",
        "ga:de",
        "pg:cr",
        "pg:re",
        "pg:up",
        "pg:de",
        "us:cr",
        "us:re",
        "us:up",
        "us:de",
    ],
    "moderator": [
        "ga:cr",
        "ga:re",
        "ga:up:own",
        "ga:de:own",
        "pg:cr",
        "pg:re",
        "pg:up:own",
        "pg:de:own",
        "us:cr",
        "us:re",
        "us:up:own",
        "us:de:own",
    ],
    "authenticated": [
        "ga:cr",
        "ga:re:own",
        "ga:up:own",
        "ga:de:own",
        "pg:re",
        "us:cr",
        "us:re:own",
        "us:up:own",
        "us:de:own",
    ],
}
