SCOPES = {
    "ga:cr": "Create new garden",
    "ga:re": "Read any garden",
    "ga:re:own": "Read own garden",
    "ga:up": "Update any garden",
    "ga:up:own": "Update own garden",
    "ga:de": "Delete any garden",
    "ga:de:own": "Delete own garden",
    "gano:cr": "Create new garden note",
    "gano:re": "Read any garden note",
    "gano:re:own": "Read own garden note",
    "gano:up": "Update any garden note",
    "gano:up:own": "Update own garden note",
    "gano:de": "Delete any garden note",
    "gano:de:own": "Delete own garden note",
    "be:cr": "Create new bed",
    "be:re": "Read any bed",
    "be:re:own": "Read own bed",
    "be:up": "Update any bed",
    "be:up:own": "Update own bed",
    "be:de": "Delete any bed",
    "be:de:own": "Delete own bed",
    "beno:cr": "Create new bed note",
    "beno:re": "Read any bed note",
    "beno:re:own": "Read own bed note",
    "beno:up": "Update any bed note",
    "beno:up:own": "Update own bed note",
    "beno:de": "Delete any bed note",
    "beno:de:own": "Delete own bed note",
    "pl:cr": "Create new plant",
    "pl:re": "Read any plant",
    "pl:re:own": "Read own plant",
    "pl:up": "Update any plant",
    "pl:up:own": "Update own plant",
    "pl:de": "Delete any plant",
    "pl:de:own": "Delete own plant",
    "plno:cr": "Create new plant",
    "plno:re": "Read any plant note",
    "plno:re:own": "Read own plant note",
    "plno:up": "Update any plant note",
    "plno:up:own": "Update own plant note",
    "plno:de": "Delete any plant note",
    "plno:de:own": "Delete own plant note",
    "pg:cr": "Create new pages",
    "pg:re": "Read any page",
    "pg:re:own": "Read own pages",
    "pg:up": "Update any page",
    "pg:up:own": "Update own pages",
    "pg:de": "Delete any page",
    "pg:de:own": "Delete own pages",
    "us:cr": "Create new uss",
    "us:re": "Read any user",
    "us:re:own": "Read own user",
    "us:up": "Update any user",
    "us:up:own": "Update own user",
    "us:de": "Delete any user",
    "us:de:own": "Delete own user",
}
