SCOPES = {
    "ga:create": "Create new garden",
    "ga:read": "Read any garden",
    "ga:read:own": "Read own garden",
    "ga:update": "Update any garden",
    "ga:update:own": "Update own garden",
    "ga:delete": "Delete any garden",
    "ga:delete:own": "Delete own garden",
    "gano:create": "Create new garden note",
    "gano:read": "Read any garden note",
    "gano:read:own": "Read own garden note",
    "gano:update": "Update any garden note",
    "gano:update:own": "Update own garden note",
    "gano:delete": "Delete any garden note",
    "gano:delete:own": "Delete own garden note",
    "be:create": "Create new bed",
    "be:read": "Read any bed",
    "be:read:own": "Read own bed",
    "be:update": "Update any bed",
    "be:update:own": "Update own bed",
    "be:delete": "Delete any bed",
    "be:delete:own": "Delete own bed",
    "beno:create": "Create new bed note",
    "beno:read": "Read any bed note",
    "beno:read:own": "Read own bed note",
    "beno:update": "Update any bed note",
    "beno:update:own": "Update own bed note",
    "beno:delete": "Delete any bed note",
    "beno:delete:own": "Delete own bed note",
    "pl:create": "Create new plant",
    "pl:read": "Read any plant",
    "pl:read:own": "Read own plant",
    "pl:update": "Update any plant",
    "pl:update:own": "Update own plant",
    "pl:delete": "Delete any plant",
    "pl:delete:own": "Delete own plant",
    "plno:create": "Create new plant",
    "plno:read": "Read any plant note",
    "plno:read:own": "Read own plant note",
    "plno:update": "Update any plant note",
    "plno:update:own": "Update own plant note",
    "plno:delete": "Delete any plant note",
    "plno:delete:own": "Delete own plant note",
    "pg:create": "Create new pages",
    "pg:read": "Read any page",
    "pg:read:own": "Read own pages",
    "pg:update": "Update any page",
    "pg:update:own": "Update own pages",
    "pg:delete": "Delete any page",
    "pg:delete:own": "Delete own pages",
    "us:create": "Create new uss",
    "us:read": "Read any user",
    "us:read:own": "Read own user",
    "us:update": "Update any user",
    "us:update:own": "Update own user",
    "us:delete": "Delete any user",
    "us:delete:own": "Delete own user",
}
