SCOPES = {
    "ad:ar": "Admin assign role",
    "ad:rr": "Admin remove role",
    "ad:cp": "Admin check permissions",
    "ad:gr": "Admin get role",
    "ga:cr": "Create new garden",
    "ga:re": "Read any garden",
    "ga:re:own": "Read own garden",
    "ga:up": "Update any garden",
    "ga:up:own": "Update own garden",
    "ga:de": "Delete any garden",
    "ga:de:own": "Delete own garden",
    "pg:cr": "Create new pages",
    "pg:re": "Read any page",
    "pg:re:own": "Read own pages",
    "pg:up": "Update any page",
    "pg:up:own": "Update own pages",
    "pg:de": "Delete any page",
    "pg:de:own": "Delete own pages",
    "us:cr": "Create new uss",
    "us:re": "Read any user",
    "us:re:own": "Read own user",
    "us:up": "Update any user",
    "us:up:own": "Update own user",
    "us:de": "Delete any user",
    "us:de:own": "Delete own user",
}
